name: demo
recipe: drupal10
config:
  webroot: web
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/web'
        # UPDATE: to the same as the name key above.
        DRUSH_OPTIONS_URI: 'http://demo.lndo.site'
tooling:
  sync:
    service: appserver
    description: Branch update (run composer / db updates / import config / clear caches).
    cmd:
      - composer install
      - drush cr
      - drush updb
      - drush cim -y
      - drush cr
  set:
    service: appserver
    description: Creates a settings.local file and installs composer dependencies
    cmd:
      - cp /app/.lando/settings.local.php /app/web/sites
      - cp /app/.lando/services.local.yml /app/web/sites
      - composer install
events:
  post-set:
    - echo "Successfully enabled local development settings and services files!"
  pre-db-import:
    # Fix MySQL 8 import issue (dropping DB with Drush). https://github.com/lando/lando/issues/2679
    - appserver: echo "Dropping the DB with Drush" && drush sql:drop -y
